#!/usr/bin/env php
<?php

use MartelliEnrico\ItunesToM3u\MyApplication;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new MyApplication('iTunes playlist converter', '1.0.0');
$app->run();